# This file was generated by GoReleaser. DO NOT EDIT.
cask "basecamp-cli" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "54c671217c467b6873acb6fa5b189aaa1673990dfc871b3e96eae7e78528250f"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "38424dbeb6b76d3f16bb7638eda7d2ad09fbf3f0894ae37ae4e470b76548e357"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bcb1fa3a03e702bbf81a3004ded4bc7808605e41106cbc768ba4006b89e0db2f"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff50313024b6ca14e40146e30e1c9c9c00a4e4103fe55615eeee3e7c359d88d1"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "basecamp-cli"
  desc "Command-line interface for Basecamp"
  homepage "https://github.com/basecamp/basecamp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "basecamp"
  bash_completion "completions/basecamp.bash"
  fish_completion "completions/basecamp.fish"
  zsh_completion "completions/_basecamp"

  # No zap stanza required

end
