# This file was generated by GoReleaser. DO NOT EDIT.
cask "basecamp" do
  name "basecamp"
  desc "Command-line interface for Basecamp"
  homepage "https://github.com/basecamp/basecamp-cli"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "basecamp"
  bash_completion "completions/basecamp.bash"
  zsh_completion "completions/_basecamp"
  fish_completion "completions/basecamp.fish"

  on_macos do
    on_intel do
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_darwin_amd64.tar.gz"
      sha256 "7e7b3d337912bd323b1a445885218960e9e7480da89f272cade793d4d6a85497"
    end
    on_arm do
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_darwin_arm64.tar.gz"
      sha256 "de4d171fe8f3a1d95bed66f4d9b2b3b67bb1475252fa02232e6204d3fdd37742"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_linux_amd64.tar.gz"
      sha256 "e33ce8fe1736d1b8b7193889f4c6bdda32c651404b3a21c467890301b3efba4c"
    end
    on_arm do
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_linux_arm64.tar.gz"
      sha256 "4e08362165420b5a28815cbcffaed188b6111bc7fa27c544ab1345f776cf8100"
    end
  end

  # No zap stanza required
end
