# This file was generated by GoReleaser. DO NOT EDIT.
cask "basecamp" do
  name "basecamp"
  desc "Command-line interface for Basecamp"
  homepage "https://github.com/basecamp/basecamp-cli"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "basecamp"
  bash_completion "completions/basecamp.bash"
  zsh_completion "completions/_basecamp"
  fish_completion "completions/basecamp.fish"

  on_macos do
    on_intel do
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_darwin_amd64.tar.gz"
      sha256 "fffb55f4a8601a2188f43c0d605ec71e93cf1e993bcafd5625963e6889555950"
    end
    on_arm do
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_darwin_arm64.tar.gz"
      sha256 "d2b2b6165dd9070f2f8ac27e7a9df583d47c91565954c8b0422f8624624221e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_linux_amd64.tar.gz"
      sha256 "39e2be72b2cca4a8cae9addd6514a21db76b9f45b2cf907a7a48ec2e6826ea74"
    end
    on_arm do
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_linux_arm64.tar.gz"
      sha256 "d7e02b9f9006a6deb429db8bfeb9f32d6579db02c04655b910ac0983507a7b80"
    end
  end

  # No zap stanza required
end
