# This file was generated by GoReleaser. DO NOT EDIT.
cask "basecamp-cli" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "99d316e991f2dad3c57ce439656a9c952651e858a107c2dd937c3fe1bada5470"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6f90a8e844a5425bfd56ade11e8736b5f115aa5502cb789217d9170f3f95726"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "55e64e0f367d06b98542e6e3057bdf0d3174da389f5406118c3c6c93f347446e"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a8daecdd6f83650c1b8dabfccc7ad6f7a724648f863d0c86253244a5467d98c5"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "basecamp-cli"
  desc "Command-line interface for Basecamp"
  homepage "https://github.com/basecamp/basecamp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "basecamp"
  bash_completion "completions/basecamp.bash"
  fish_completion "completions/basecamp.fish"
  zsh_completion "completions/_basecamp"

  # No zap stanza required

end
