# This file was generated by GoReleaser. DO NOT EDIT.
cask "basecamp-cli" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "9a1c932b83d099c15b7cf97d4b03a798b3e00c649a0eb0416cc25c0f354a501f"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "01224552bd3a190c171ab78324133c32f199264132540b4c452d4b17047d1d5b"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca8b3a085f90323c8ab1694b83ff624cf10c459618ca6010ce204534f3f01987"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd1b5db88b9b309e95ae1ec0d642d23f4955a3abe159bffe00796a0ef6030c1d"
      url "https://github.com/basecamp/basecamp-cli/releases/download/v#{version}/basecamp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "basecamp-cli"
  desc "Command-line interface for Basecamp"
  homepage "https://github.com/basecamp/basecamp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "basecamp"
  bash_completion "completions/basecamp.bash"
  fish_completion "completions/basecamp.fish"
  zsh_completion "completions/_basecamp"

  # No zap stanza required

end
