# This file was generated by GoReleaser. DO NOT EDIT.
cask "fizzy" do
  name "fizzy"
  desc "CLI for managing Fizzy boards, cards, and tasks"
  homepage "https://github.com/basecamp/fizzy-cli"
  version "4.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fizzy"
  bash_completion "completions/fizzy.bash"
  zsh_completion "completions/fizzy.zsh"
  fish_completion "completions/fizzy.fish"

  on_macos do
    on_intel do
      url "https://github.com/basecamp/fizzy-cli/releases/download/v#{version}/fizzy_#{version}_darwin_amd64.tar.gz"
      sha256 "f6ac2f55c9b514bd50ef1b3f41bbcd6cf3873199b00914173b270d0ebdf6cf20"
    end
    on_arm do
      url "https://github.com/basecamp/fizzy-cli/releases/download/v#{version}/fizzy_#{version}_darwin_arm64.tar.gz"
      sha256 "111b6bcb200b79b7bbfd075b80f0bb90541566e0d8cb12abb30b988dbba8fd64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/basecamp/fizzy-cli/releases/download/v#{version}/fizzy_#{version}_linux_amd64.tar.gz"
      sha256 "8a3a6b48d6eb732a189a3b18d863a1db6497a55926fd6efa4ace92e9d0a30572"
    end
    on_arm do
      url "https://github.com/basecamp/fizzy-cli/releases/download/v#{version}/fizzy_#{version}_linux_arm64.tar.gz"
      sha256 "b96a0522929b28931a68fc11c2c5b957990d10caa831629252831631bba89dde"
    end
  end

  # No zap stanza required
end
