# This file was generated by GoReleaser. DO NOT EDIT.
cask "fizzy" do
  name "fizzy"
  desc "CLI for managing Fizzy boards, cards, and tasks"
  homepage "https://github.com/basecamp/fizzy-cli"
  version "4.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fizzy"
  bash_completion "completions/fizzy.bash"
  zsh_completion "completions/fizzy.zsh"
  fish_completion "completions/fizzy.fish"

  on_macos do
    on_intel do
      url "https://github.com/basecamp/fizzy-cli/releases/download/v#{version}/fizzy_#{version}_darwin_amd64.tar.gz"
      sha256 "b5a734e70b16d768ba309604ea468c77dc7ca9a704e09d6946b9ae63a5b6036d"
    end
    on_arm do
      url "https://github.com/basecamp/fizzy-cli/releases/download/v#{version}/fizzy_#{version}_darwin_arm64.tar.gz"
      sha256 "bafacd5916cd94beb0d895fa4485501881da63c48222da6df60bcf2e81f3e193"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/basecamp/fizzy-cli/releases/download/v#{version}/fizzy_#{version}_linux_amd64.tar.gz"
      sha256 "007359aeea7db7f88386d09e83d3b3603bd5139d9729da107c29416133aa94ee"
    end
    on_arm do
      url "https://github.com/basecamp/fizzy-cli/releases/download/v#{version}/fizzy_#{version}_linux_arm64.tar.gz"
      sha256 "0abe9cfa2a6983993e2f9b1cd57a4c1540a49b88365231e6318a244c19cd7ed5"
    end
  end

  # No zap stanza required
end
