# This file was generated by GoReleaser. DO NOT EDIT.
cask "hey" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "15b91311a4041c5fb07f56d270455c63e7382a78668aa4d10dc7103509cf34d4"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "31bdff170c83718c03a73775806f9a6657cad267ea0c2e76e4cd644cd903b9de"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b450104ee0205e0481194dd9031f060228025aa501c170498f5e6285f867b9b3"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd451e24415b35a9208b64b319a3022f76cdb21184ba1219deacb41702c26de7"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hey"
  desc "Command-line interface for HEY email"
  homepage "https://github.com/basecamp/hey-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hey"
  bash_completion "completions/hey.bash"
  fish_completion "completions/hey.fish"
  zsh_completion "completions/_hey"

  # No zap stanza required

end
