# This file was generated by GoReleaser. DO NOT EDIT.
cask "hey" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "969d6480fd5342e5517e6d1f165103363a7c1bbb3dd90cde70d3a4ba23076def"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "706605c7bd1b9dde1149f6dca4a1a60713a8617f8e8e7dc878b8e2cf18fa5a46"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "316423686028bbbc999cf0ee0443d9ca73a737681c1515588470774f2b394f10"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7cb79d265d5491a9d9967c00e36d748bcec0021d0d52c64163d7b8a8bb528466"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hey"
  desc "Command-line interface for HEY email"
  homepage "https://github.com/basecamp/hey-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hey"
  bash_completion "completions/hey.bash"
  fish_completion "completions/hey.fish"
  zsh_completion "completions/_hey"

  # No zap stanza required

end
