# This file was generated by GoReleaser. DO NOT EDIT.
cask "hey" do
  version "1.4.1"

  on_macos do
    on_intel do
      sha256 "dbcf073ecd2667b5b5f345e4fcbf6e41472807a0c687c408b73064afaea12001"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e02d96039290243349db106a03f1524be3133371df04ad7134fe0fe85781e190"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18c4a5eb86dc98a7416fd6c452537a0968df7080cda6c20bd9192f06d95e58b1"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a7e3124e8b09313f013dee9f72bef7d302cff27e5e2d7f36571c30b5289ab58"
      url "https://github.com/basecamp/hey-cli/releases/download/v#{version}/hey_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hey"
  desc "Command-line interface for HEY email"
  homepage "https://github.com/basecamp/hey-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hey"
  bash_completion "completions/hey.bash"
  fish_completion "completions/hey.fish"
  zsh_completion "completions/_hey"

  # No zap stanza required

end
